return {
  None              = "NONE",
  Debug             = "#FF00FF",
--  Comment           = "#435f37",
  Comment           = "#405c37",
  Parameter         = "#9a9a9a",
  Type              = "#4EC9B0",
  Namespace         = "#cffae4",
  Global            = "#F8D1EF",
  Property          = "#DADADA",
  SelfParameter     = "#CAC4FF",
  Numeric           = "#b5cea8",
  Invalid           = "#f44747",
  Macro             = "#cac4ff",
  MacroFunction     = "#cac4ff",
  Normal            = "#343434",
  Preprocessor      = "#9b9b9b",
  Keyword           = "#569CD6",
  VariableLocal     = "#9CDCFE",
  Variable          = "#343434",
  VariableBuiltin   = "#3d739f",
  ControlFlow       = "#C586C0",
}
